# Generated by Django 6.0 on 2026-01-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional featured image for the article', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
